config/routes.rb
SearchSample::Application.routes.draw do

  resources :products, only: [:index] do
    collection do
      post :search
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @search_product = SearchProduct.new
    @products = Product.all
  end

  def search
    @search_product = SearchProduct.new(product_params_as_search)
    unless @products = @search_product.search
      @products = Product.all
    end
    render :index
  end

  private

    def product_params_as_search
      params.require(:search_product).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchSample</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<% if @search_product.errors.any? %>
  <ul>
    <% @search_product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@search_product, url: search_products_path) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit '検索' %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= Product.human_attribute_name(:name) %></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>